<?php

/**
 * @file
 * Contains ea_events.module.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_alter().
 *
 * Control visibility for Event Repeater entities.
 */
function ea_events_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if ($form_id === 'event_repeater_add_form' || $form_id === 'event_repeater_edit_form') {
    _ea_events_get_event_repeater_states($form);
  }
}

/**
 * Implements hook_inline_entity_form_entity_form_alter().
 *
 * Control visibility for inline Event Repeater entities.
 */
function ea_events_inline_entity_form_entity_form_alter(&$entity_form, FormStateInterface $form_state) {
  if ($entity_form['#entity_type'] === 'event_repeater') {
    _ea_events_get_event_repeater_states($entity_form, 'event_repeater[0][inline_entity_form]');
  }
}

/**
 * Return event states.
 *
 * @param array $form
 *   The form array to add states to.
 * @param string $extra_identifier
 *   An optional string to identify inputs.
 */
function _ea_events_get_event_repeater_states(&$form, $extra_identifier = NULL) {
  $startBracket = strlen($extra_identifier) > 0 ? '[' : '';
  $endBracket = strlen($extra_identifier) > 0 ? ']' : '';
  $form['event_interval']['#states'] = array(
    'invisible' => array(
      ':input[name="' . $extra_identifier . $startBracket . 'event_freq' . $endBracket . '"]' => array('value' => 'none'),
    ),
  );
  $form['event_ends']['#states'] = array(
    'invisible' => array(
      ':input[name="' . $extra_identifier . $startBracket . 'event_freq' . $endBracket . '"]' => array('value' => 'none'),
    ),
  );
  $form['event_byday_multiple']['#states'] = array(
    'visible' => array(
      ':input[name="' . $extra_identifier . $startBracket . 'event_freq' . $endBracket . '"]' => array('value' => 'WEEKLY'),
    ),
  );
  $form['event_repeat_by']['#states'] = array(
    'visible' => array(
      array(
        ':input[name="' . $extra_identifier . $startBracket . 'event_freq' . $endBracket . '"]' => array('value' => 'MONTHLY'),
      ),
      array(
        ':input[name="' . $extra_identifier . $startBracket . 'event_freq' . $endBracket . '"]' => array('value' => 'YEARLY'),
      ),
    ),
  );
  $form['event_count']['#states'] = array(
    'invisible' => array(
      ':input[name="' . $extra_identifier . $startBracket . 'event_freq' . $endBracket . '"]' => array('value' => 'none'),
    ),
  );
  $form['event_bymonthday']['#states'] = array(
    'visible' => array(
      array(
        ':input[name="' . $extra_identifier . $startBracket . 'event_repeat_by' . $endBracket . '"]' => array('value' => 'day_of_the_month'),
        ':input[name="' . $extra_identifier . $startBracket . 'event_freq' . $endBracket . '"]' => array('value' => 'MONTHLY'),
      ),
      array(
        ':input[name="' . $extra_identifier . $startBracket . 'event_repeat_by' . $endBracket . '"]' => array('value' => 'day_of_the_month'),
        ':input[name="' . $extra_identifier . $startBracket . 'event_freq' . $endBracket . '"]' => array('value' => 'YEARLY'),
      ),
    ),
  );
  $form['event_bysetpos']['#states'] = array(
    'visible' => array(
      array(
        ':input[name="' . $extra_identifier . $startBracket . 'event_repeat_by' . $endBracket . '"]' => array('value' => 'day_of_the_week'),
        ':input[name="' . $extra_identifier . $startBracket . 'event_freq' . $endBracket . '"]' => array('value' => 'MONTHLY'),
      ),
      array(
        ':input[name="' . $extra_identifier . $startBracket . 'event_repeat_by' . $endBracket . '"]' => array('value' => 'day_of_the_week'),
        ':input[name="' . $extra_identifier . $startBracket . 'event_freq' . $endBracket . '"]' => array('value' => 'YEARLY'),
      ),
    ),
  );
  $form['event_byday']['#states'] = array(
    'visible' => array(
      array(
        ':input[name="' . $extra_identifier . $startBracket . 'event_repeat_by' . $endBracket . '"]' => array('value' => 'day_of_the_week'),
        ':input[name="' . $extra_identifier . $startBracket . 'event_freq' . $endBracket . '"]' => array('value' => 'MONTHLY'),
      ),
      array(
        ':input[name="' . $extra_identifier . $startBracket . 'event_repeat_by' . $endBracket . '"]' => array('value' => 'day_of_the_week'),
        ':input[name="' . $extra_identifier . $startBracket . 'event_freq' . $endBracket . '"]' => array('value' => 'YEARLY'),
      ),
    ),
  );
  $form['event_bymonth']['#states'] = array(
    'visible' => array(
      ':input[name="' . $extra_identifier . $startBracket . 'event_repeat_by' . $endBracket . '"]' => array('value' => 'day_of_the_week'),
      ':input[name="' . $extra_identifier . $startBracket . 'event_freq' . $endBracket . '"]' => array('value' => 'YEARLY'),
    ),
  );
  $form['event_count']['#states'] = array(
    'visible' => array(
      ':input[name="' . $extra_identifier . $startBracket . 'event_ends' . $endBracket . '"]' => array('value' => 'COUNT'),
      ':input[name="' . $extra_identifier . $startBracket . 'event_freq' . $endBracket . '"]' => array('!value' => 'none'),
    ),
  );
  $form['event_until']['#states'] = array(
    'visible' => array(
      ':input[name="' . $extra_identifier . $startBracket . 'event_ends' . $endBracket . '"]' => array('value' => 'UNTIL'),
      ':input[name="' . $extra_identifier . $startBracket . 'event_freq' . $endBracket . '"]' => array('!value' => 'none'),
    ),
  );
  return $form;
}
