<?php

/**
 * @file
 * Contains effective_activism.module.
 */

use Drupal\Core\Url;

/**
 * Implements hook_toolbar().
 */
function effective_activism_toolbar() {
  // Define tab links.
  $organizer_links = array(
    'ea_groupings' => array(
      'title' => t('Groupings'),
      'url' => Url::fromRoute('entity.grouping.collection'),
      'attributes' => array(
        'title' => t('Groupings'),
      ),
    ),
    'ea_events' => array(
      'title' => t('Events'),
      'url' => Url::fromRoute('entity.event.collection'),
      'attributes' => array(
        'title' => t('Events'),
      ),
    ),
    'ea_imports' => array(
      'title' => t('Imports'),
      'url' => Url::fromRoute('entity.import.collection'),
      'attributes' => array(
        'title' => t('Imports'),
      ),
    ),
    'ea_people' => array(
      'title' => t('People'),
      'url' => Url::fromRoute('entity.person.collection'),
      'attributes' => array(
        'title' => t('People'),
      ),
    ),
    'ea_tasks' => array(
      'title' => t('Tasks'),
      'url' => Url::fromRoute('entity.task.collection'),
      'attributes' => array(
        'title' => t('Tasks'),
      ),
    ),
    'results' => array(
      'title' => t('Results'),
      'url' => Url::fromRoute('entity.result.collection'),
      'attributes' => array(
        'title' => t('Results'),
      ),
    ),
  );
  $manager_links = array(
    'ea_groupings' => array(
      'title' => t('Groupings'),
      'url' => Url::fromRoute('entity.grouping.collection'),
      'attributes' => array(
        'title' => t('Groupings'),
      ),
    ),
    'ea_events' => array(
      'title' => t('Events'),
      'url' => Url::fromRoute('entity.event.collection'),
      'attributes' => array(
        'title' => t('Events'),
      ),
    ),
    'ea_results_types' => array(
      'title' => t('Result types'),
      'url' => Url::fromRoute('entity.result_type.collection'),
      'attributes' => array(
        'title' => t('Result types'),
      ),
    ),
    'ea_imports' => array(
      'title' => t('Imports'),
      'url' => Url::fromRoute('entity.import.collection'),
      'attributes' => array(
        'title' => t('Imports'),
      ),
    ),
    'ea_people' => array(
      'title' => t('People'),
      'url' => Url::fromRoute('entity.person.collection'),
      'attributes' => array(
        'title' => t('People'),
      ),
    ),
    'ea_tasks' => array(
      'title' => t('Tasks'),
      'url' => Url::fromRoute('entity.task.collection'),
      'attributes' => array(
        'title' => t('Tasks'),
      ),
    ),
    'results' => array(
      'title' => t('Results'),
      'url' => Url::fromRoute('entity.result.collection'),
      'attributes' => array(
        'title' => t('Results'),
      ),
    ),
    'organization' => array(
      'title' => t('Add organization'),
      'url' => Url::fromRoute('ea_groupings.add_organization'),
      'attributes' => array(
        'title' => t('Add organization'),
      ),
    ),
  );
  // Construct toolbar link and tab.
  $items = array();
  $items['effective_activism'] = array(
    '#type' => 'toolbar_item',
    'tab' => array(
      '#type' => 'link',
      '#title' => t('Effective Activism'),
      '#url' => Url::fromRoute('effective_activism.overview'),
      '#options' => array(
        'attributes' => array(
          'title' => t('Effective Activism'),
        ),
      ),
    ),
    '#weight' => 1,
    'tray' => array(
      '#heading' => t('Overview'),
      'effective_activism_links' => array(
        '#theme' => 'links__toolbar_user',
        '#links' => $manager_links,
      ),
    ),
  );
  return $items;
}
