ea_activities.activity_type.*:
  type: config_entity
  label: 'Activity type config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    description:
      type: string
      label: 'Description'
    data_types:
      type: sequence
      label: 'Data types'
      sequence:
        type: mapping
        mapping:
          target_id:
           type: string
    uuid:
      type: string
