<?php

/**
 * @file
 * Contains ea_data.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_help().
 */
function ea_data_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the ea_data module.
    case 'help.page.ea_data':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function ea_data_theme() {
  $theme = [];
  $theme['data'] = [
    'render element' => 'elements',
    'file' => 'data.page.inc',
    'template' => 'data',
  ];
  $theme['data_content_add_list'] = [
    'render element' => 'content',
    'variables' => ['content' => NULL],
    'file' => 'data.page.inc',
  ];
  return $theme;
}

/**
 * Implements hook_inline_entity_form_entity_form_alter().
 */
function ea_data_inline_entity_form_entity_form_alter(&$entity_form, FormStateInterface $form_state) {
  if ($entity_form['#entity_type'] === 'data') {
    // Hide revision and user fields.
    $entity_form['user_id']['#attributes']['class'][] = 'hidden';
    $entity_form['revision_log_message']['#attributes']['class'][] = 'hidden';
  }
}
