<?php

/**
 * @file
 * Contains ea_groupings.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_help().
 */
function ea_groupings_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the ea_groupings module.
    case 'help.page.ea_groupings':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Manages organizations and groups.') . '</p>';
      return $output;
    default:
  }
}

/**
 * Implements hook_form_alter().
 * 
 * Hide managers entity reference field for groupings with a parent.
 * Only when a grouping is parent do we allow the manager field to be set.
 */
function ea_groupings_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if ($form_id === 'grouping_edit_form' || $form_id === 'grouping_add_form') {
    $form['managers']['#states'] = array(
      'invisible' => array(
        ':input[name="parent[0][target_id]"]' => array('filled' => TRUE),
      )
    );
  }
}
