<?php

/**
 * @file
 * Contains ea_tasks.module.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_inline_entity_form_entity_form_alter().
 */
function ea_tasks_inline_entity_form_entity_form_alter(&$entity_form, FormStateInterface $form_state) {
  if ($entity_form['#entity_type'] === 'task') {
    // Hide revision and user fields.
    $entity_form['user_id']['#attributes']['class'][] = 'hidden';
    $entity_form['revision_log_message']['#attributes']['class'][] = 'hidden';
  }
}
