ea_data.data_type.*:
  type: config_entity
  label: 'Data type config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    description:
      type: string
      label: 'Description'
    uuid:
      type: string
