ea_results.result_type.*:
  type: config_entity
  label: 'Result type config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    description:
      type: string
      label: 'Description'
    data_types:
      type: sequence
      label: 'Data types'
      sequence:
        type: string
    organization:
      type: integer
      label: 'Data types'
    groupings:
      type: sequence
      label: 'Groupings'
      sequence:
        type: integer
    uuid:
      type: string
